"""
Initial schema

Revision ID: b819250c7a7c
Revises: 
Create Date: 2026-02-01 20:20:14.560860+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Revision identifiers
revision: str = 'b819250c7a7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licence', sa.String(length=20), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('ligue', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arbitres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arbitres_licence'), ['licence'], unique=True)
        batch_op.create_index(batch_op.f('ix_arbitres_nom'), ['nom'], unique=False)

    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('ligue', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'ligue', name='uq_club_nom_ligue')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clubs_ligue'), ['ligue'], unique=False)
        batch_op.create_index(batch_op.f('ix_clubs_nom'), ['nom'], unique=False)
        batch_op.create_index('ix_clubs_nom_ligue', ['nom', 'ligue'], unique=False)

    op.create_table('joueurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licence', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('nationalite', sa.String(length=50), nullable=True),
    sa.Column('matchs_joues', sa.Integer(), nullable=False),
    sa.Column('sets_joues', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_joueurs_licence'), ['licence'], unique=True)
        batch_op.create_index(batch_op.f('ix_joueurs_nom'), ['nom'], unique=False)
        batch_op.create_index('ix_joueurs_nom_prenom', ['nom', 'prenom'], unique=False)

    op.create_table('saisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=9), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=True),
    sa.Column('categorie', sa.String(length=20), nullable=True),
    sa.Column('niveau', sa.String(length=50), nullable=True),
    sa.Column('ligue', sa.String(length=50), nullable=True),
    sa.Column('saison_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saison_id'], ['saisons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'saison_id', name='uq_competition_code_saison')
    )
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('nom_court', sa.String(length=100), nullable=True),
    sa.Column('categorie', sa.String(length=20), nullable=True),
    sa.Column('genre', sa.String(length=20), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipes_nom'), ['nom'], unique=False)

    op.create_table('joueur_equipe',
    sa.Column('joueur_id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('saison_id', sa.Integer(), nullable=True),
    sa.Column('est_libero', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['joueur_id'], ['joueurs.id'], ),
    sa.ForeignKeyConstraint(['saison_id'], ['saisons.id'], ),
    sa.PrimaryKeyConstraint('joueur_id', 'equipe_id')
    )
    op.create_table('matchs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_match', sa.String(length=30), nullable=False),
    sa.Column('date_match', sa.Date(), nullable=True),
    sa.Column('heure_match', sa.Time(), nullable=True),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('salle', sa.String(length=200), nullable=True),
    sa.Column('journee', sa.String(length=20), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('saison_id', sa.Integer(), nullable=True),
    sa.Column('equipe_a_id', sa.Integer(), nullable=True),
    sa.Column('equipe_b_id', sa.Integer(), nullable=True),
    sa.Column('vainqueur_id', sa.Integer(), nullable=True),
    sa.Column('vainqueur_nom', sa.String(length=200), nullable=True),
    sa.Column('score_final', sa.String(length=10), nullable=True),
    sa.Column('sets_equipe_a', sa.Integer(), nullable=False),
    sa.Column('sets_equipe_b', sa.Integer(), nullable=False),
    sa.Column('duree_totale', sa.String(length=20), nullable=True),
    sa.Column('remarques', sa.Text(), nullable=True),
    sa.Column('source_pdf', sa.String(length=500), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['equipe_a_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['equipe_b_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['saison_id'], ['saisons.id'], ),
    sa.ForeignKeyConstraint(['vainqueur_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_match', 'saison_id', name='uq_match_code_saison')
    )
    with op.batch_alter_table('matchs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matchs_code_match'), ['code_match'], unique=False)
        batch_op.create_index('ix_matchs_date', ['date_match'], unique=False)

    op.create_table('arbitre_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arbitre_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['arbitre_id'], ['arbitres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matchs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arbitre_id', 'match_id', 'role', name='uq_arbitre_match_role')
    )
    op.create_table('participations_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('joueur_id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('numero_maillot', sa.String(length=5), nullable=True),
    sa.Column('est_capitaine', sa.Boolean(), nullable=False),
    sa.Column('est_libero', sa.Boolean(), nullable=False),
    sa.Column('est_titulaire', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['joueur_id'], ['joueurs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matchs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'joueur_id', name='uq_participation')
    )
    with op.batch_alter_table('participations_match', schema=None) as batch_op:
        batch_op.create_index('ix_participation_match_joueur', ['match_id', 'joueur_id'], unique=False)

    op.create_table('sanctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('joueur_id', sa.Integer(), nullable=True),
    sa.Column('type_sanction', sa.String(length=1), nullable=False),
    sa.Column('set_numero', sa.Integer(), nullable=False),
    sa.Column('equipe', sa.String(length=1), nullable=False),
    sa.Column('joueur_numero', sa.String(length=5), nullable=True),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['joueur_id'], ['joueurs.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matchs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('heure_debut', sa.String(length=8), nullable=True),
    sa.Column('heure_fin', sa.String(length=8), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('service_initial', sa.String(length=1), nullable=True),
    sa.Column('formation_a', sa.Text(), nullable=True),
    sa.Column('formation_b', sa.Text(), nullable=True),
    sa.Column('timeouts_a', sa.Text(), nullable=True),
    sa.Column('timeouts_b', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matchs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets')
    op.drop_table('sanctions')
    with op.batch_alter_table('participations_match', schema=None) as batch_op:
        batch_op.drop_index('ix_participation_match_joueur')

    op.drop_table('participations_match')
    op.drop_table('arbitre_match')
    with op.batch_alter_table('matchs', schema=None) as batch_op:
        batch_op.drop_index('ix_matchs_date')
        batch_op.drop_index(batch_op.f('ix_matchs_code_match'))

    op.drop_table('matchs')
    op.drop_table('joueur_equipe')
    with op.batch_alter_table('equipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipes_nom'))

    op.drop_table('equipes')
    op.drop_table('competitions')
    op.drop_table('saisons')
    with op.batch_alter_table('joueurs', schema=None) as batch_op:
        batch_op.drop_index('ix_joueurs_nom_prenom')
        batch_op.drop_index(batch_op.f('ix_joueurs_nom'))
        batch_op.drop_index(batch_op.f('ix_joueurs_licence'))

    op.drop_table('joueurs')
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index('ix_clubs_nom_ligue')
        batch_op.drop_index(batch_op.f('ix_clubs_nom'))
        batch_op.drop_index(batch_op.f('ix_clubs_ligue'))

    op.drop_table('clubs')
    with op.batch_alter_table('arbitres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arbitres_nom'))
        batch_op.drop_index(batch_op.f('ix_arbitres_licence'))

    op.drop_table('arbitres')
    # ### end Alembic commands ###
