"""
Update

Revision ID: 3a0c7a8a3c41
Revises: f6b8c0d45e00
Create Date: 2026-03-02 21:07:27.566513+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Revision identifiers
revision: str = '3a0c7a8a3c41'
down_revision: Union[str, None] = 'f6b8c0d45e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
