"""
Add import_logs audit table

Revision ID: fb7007e4840a
Revises: f6b8c0d45e00
Create Date: 2026-03-06 11:33:30.807814+00:00
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Revision identifiers
revision: str = 'fb7007e4840a'
down_revision: Union[str, None] = 'f6b8c0d45e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('total_attempted', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_logs', schema=None) as batch_op:
        batch_op.create_index('ix_import_logs_operation', ['operation'], unique=False)
        batch_op.create_index('ix_import_logs_started_at', ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_import_logs_started_at')
        batch_op.drop_index('ix_import_logs_operation')

    op.drop_table('import_logs')
    # ### end Alembic commands ###
