"""
Migration Service for PyVolley

This module provides a high-level interface for managing database migrations
using Alembic. It supports:
- Creating new migrations (autogenerated or empty)
- Upgrading/downgrading the database
- Checking migration status
- Resetting the database with migrations
"""

import logging
from pathlib import Path
from typing import Optional

from alembic import command
from alembic.config import Config
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import inspect

from ..core.config import get_settings
from .connection import get_engine

logger = logging.getLogger(__name__)


def get_alembic_config() -> Config:
    """
    Get Alembic configuration with PyVolley settings.

    Returns:
        Alembic Config object configured for PyVolley
    """
    settings = get_settings()

    # Find alembic.ini
    project_root = Path(__file__).parent.parent.parent.parent
    alembic_ini = project_root / "alembic.ini"

    if not alembic_ini.exists():
        raise FileNotFoundError(
            f"alembic.ini not found at {alembic_ini}. "
            "Please run from the project root directory."
        )

    alembic_cfg = Config(str(alembic_ini))
    alembic_cfg.set_main_option("script_location", str(project_root / "alembic"))
    alembic_cfg.set_main_option("prepend_sys_path", str(project_root))
    alembic_cfg.set_main_option("sqlalchemy.url", settings.database_url)

    return alembic_cfg


def create_migration(message: str, autogenerate: bool = True) -> Optional[str]:
    """
    Create a new migration script.

    Args:
        message: Description of the migration
        autogenerate: If True, auto-detect changes from models

    Returns:
        Path to the created migration script, or None if no changes detected
    """
    alembic_cfg = get_alembic_config()

    try:
        script = command.revision(
            alembic_cfg,
            message=message,
            autogenerate=autogenerate,
        )

        if script:
            if isinstance(script, list):
                first_script = script[0] if script else None
                return first_script.path if first_script else None
            return script.path
        return None

    except Exception as e:
        raise RuntimeError(f"Failed to create migration: {e}") from e


def upgrade(revision: str = "head") -> None:
    """
    Upgrade database to a specific revision.

    Args:
        revision: Target revision (default: "head" for latest)
    """
    alembic_cfg = get_alembic_config()
    command.upgrade(alembic_cfg, revision)


def downgrade(revision: str = "-1") -> None:
    """
    Downgrade database to a previous revision.

    Args:
        revision: Target revision (default: "-1" for one step back)
    """
    alembic_cfg = get_alembic_config()
    command.downgrade(alembic_cfg, revision)


def get_current_revision() -> Optional[str]:
    """
    Get the current database revision.

    Returns:
        Current revision ID, or None if no migrations applied
    """
    engine = get_engine()

    with engine.connect() as conn:
        context = MigrationContext.configure(conn)
        return context.get_current_revision()


def get_head_revision() -> Optional[str]:
    """
    Get the head (latest) revision from migration scripts.

    Returns:
        Head revision ID, or None if no migrations exist
    """
    alembic_cfg = get_alembic_config()
    script = ScriptDirectory.from_config(alembic_cfg)
    return script.get_current_head()


def get_pending_migrations() -> list[str]:
    """
    Get list of pending migrations not yet applied.

    Returns:
        List of revision IDs that haven't been applied
    """
    alembic_cfg = get_alembic_config()
    script = ScriptDirectory.from_config(alembic_cfg)
    engine = get_engine()

    with engine.connect() as conn:
        context = MigrationContext.configure(conn)
        current = context.get_current_revision()

    head = script.get_current_head()

    # If up to date or no migrations exist
    if current == head:
        return []
    if head is None:
        return []

    # Collect revisions between head and current
    pending = []
    try:
        for rev in script.walk_revisions():
            if rev.revision == current:
                break
            pending.append(rev.revision)
    except Exception as e:
        logger.warning("Could not walk revision tree: %s", e)
        # Fallback: if DB has no revision, everything is pending
        if current is None:
            try:
                for rev in script.walk_revisions():
                    pending.append(rev.revision)
            except Exception:
                pass

    return pending


def check_migrations_needed() -> bool:
    """
    Check if there are pending migrations to apply.

    Returns:
        True if there are pending migrations, False otherwise
    """
    return len(get_pending_migrations()) > 0


def get_migration_history() -> list[dict]:
    """
    Get the history of all migrations.

    Returns:
        List of migration info dicts with revision, description, etc.
    """
    alembic_cfg = get_alembic_config()
    script = ScriptDirectory.from_config(alembic_cfg)
    current = get_current_revision()

    history = []

    # Collect applied revisions by walking from current down
    applied_revisions: set[str] = set()
    if current:
        found_current = False
        try:
            for rev in script.walk_revisions():
                if rev.revision == current:
                    found_current = True
                if found_current:
                    applied_revisions.add(rev.revision)
        except Exception:
            applied_revisions.add(current)

    # Walk all revisions from head to base
    try:
        for revision in script.walk_revisions():
            history.append({
                "revision": revision.revision,
                "down_revision": revision.down_revision,
                "description": revision.doc,
                "is_current": revision.revision == current,
                "is_applied": revision.revision in applied_revisions,
            })
    except Exception as e:
        logger.warning("Could not build migration history: %s", e)

    return history


def stamp(revision: str = "head") -> None:
    """
    Stamp the database with a specific revision without running migrations.

    Useful for initializing alembic on an existing database.

    Args:
        revision: Revision to stamp (default: "head")
    """
    alembic_cfg = get_alembic_config()
    command.stamp(alembic_cfg, revision)


def reset_database_with_migrations() -> None:
    """
    Reset the database and apply all migrations from scratch.

    WARNING: This will delete all data!
    """
    from .connection import drop_db

    drop_db()
    upgrade("head")


def ensure_database_ready() -> None:
    """
    Ensure the database is ready with all migrations applied.

    This is the main entry point for database initialization.
    It will:
    1. Check if migrations exist
    2. Apply any pending migrations
    3. If no migrations exist, create initial migration and apply it
    """
    alembic_cfg = get_alembic_config()
    script = ScriptDirectory.from_config(alembic_cfg)

    if script.get_current_head() is None:
        logger.info("No migrations found. Creating initial migration...")
        create_migration("Initial schema", autogenerate=True)

    pending = get_pending_migrations()
    if pending:
        logger.info("Applying %d pending migration(s)...", len(pending))
        upgrade("head")
        logger.info("Migrations applied successfully.")
    else:
        current = get_current_revision()
        if current is None:
            logger.info("Applying migrations to new database...")
            upgrade("head")
            logger.info("Database initialized successfully.")
        else:
            logger.debug("Database is up to date.")


def check_tables_exist() -> bool:
    """
    Check if the main database tables exist.

    Returns:
        True if tables exist, False otherwise
    """
    engine = get_engine()
    inspector = inspect(engine)
    tables = inspector.get_table_names()

    required_tables = ["matchs", "clubs", "equipes", "joueurs"]
    return all(table in tables for table in required_tables)


def get_database_status() -> dict:
    """
    Get comprehensive database status information.

    Returns:
        Dict with database status info
    """
    settings = get_settings()
    engine = get_engine()

    try:
        inspector = inspect(engine)
        tables = inspector.get_table_names()

        current_rev = get_current_revision()
        head_rev = get_head_revision()

        # Compute pending count safely
        try:
            pending = get_pending_migrations()
            pending_count = len(pending)
        except Exception:
            pending_count = 0 if current_rev == head_rev else -1

        return {
            "connected": True,
            "database_type": "postgresql" if settings.is_postgres else "sqlite",
            "database_url": (
                settings.database_url.split("@")[-1]
                if "@" in settings.database_url
                else settings.database_url
            ),
            "tables": tables,
            "table_count": len(tables),
            "current_revision": current_rev,
            "head_revision": head_rev,
            "pending_migrations": pending_count,
            "is_up_to_date": current_rev == head_rev and current_rev is not None,
        }
    except Exception as e:
        return {
            "connected": False,
            "error": str(e),
            "database_type": "postgresql" if settings.is_postgres else "sqlite",
        }
